// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package likes

// Fill with you ideas below.
const (
	Do   = 1
	Undo = 0
)
