// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package users

const (
	NormalStatus    = 0
	ForbiddenStatus = 1
)
